services:
  backend:
    build:
      context: ./backend
    image: simple-python-backend:latest
    container_name: simple-backend

  frontend:
    build:
      context: ./frontend
    image: simple-python-frontend:latest
    container_name: simple-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend